w = list('бвгджзйклмнпрстфхцчшщ')
for i in range(0, 100):
    i += 1
    text = input('Введите текст:')
    lang = input('Выберите поросячий язык:')
    if lang in w:
        text1 = text.replace('а', '{}{}{}'.format('а', lang, 'а'))
        text2 = text1.replace('А', '{}{}{}'.format('А', lang, 'а'))
        text3 = text2.replace('о', '{}{}{}'.format('о', lang, 'о'))
        text4 = text3.replace('О', '{}{}{}'.format('О', lang, 'о'))
        text5 = text4.replace('и', '{}{}{}'.format('и', lang, 'и'))
        text6 = text5.replace('И', '{}{}{}'.format('И', lang, 'и'))
        text7 = text6.replace('е', '{}{}{}'.format('е', lang, 'е'))
        text8 = text7.replace('Е', '{}{}{}'.format('Е', lang, 'е'))
        text9 = text8.replace('ё', '{}{}{}'.format('ё', lang, 'ё'))
        text10 = text9.replace('Ё', '{}{}{}'.format('Ё', lang, 'ё'))
        text11 = text10.replace('э', '{}{}{}'.format('э', lang, 'э'))
        text12= text11.replace('Э', '{}{}{}'.format('Э', lang, 'э'))
        text13 = text12.replace('ы', '{}{}{}'.format('ы', lang, 'ы'))
        text14= text13.replace('Ы', '{}{}{}'.format('Ы', lang, 'ы'))
        text15= text14.replace('у', '{}{}{}'.format('у', lang, 'у'))
        text16= text15.replace('У', '{}{}{}'.format('У', lang, 'а'))
        text17= text16.replace('ю', '{}{}{}'.format('ю', lang, 'ю'))
        text18= text17.replace('Ю', '{}{}{}'.format('Ю', lang, 'ю'))
        text19= text18.replace('я', '{}{}{}'.format('я', lang, 'я'))
        text20 = text19.replace('Я', '{}{}{}'.format('Я', lang, 'я'))
        print(text20)
