w = list('бвгджзйклмнпрстфхцчшщ')
ch = int(input('Напишите 1, если хотите перевести с русского на поросячий, 2 если с поросячего на русский:'))
if ch == 1:
    for i in range(0, 100):
        i += 1
        text = input('Введите текст:')
        lang = input('Выберите поросячий язык:')
        if lang in w:
            text1 = text.replace('а', '{}{}{}'.format('а', lang, 'а'))
            text2 = text1.replace('А', '{}{}{}'.format('А', lang, 'а'))
            text3 = text2.replace('о', '{}{}{}'.format('о', lang, 'о'))
            text4 = text3.replace('О', '{}{}{}'.format('О', lang, 'о'))
            text5 = text4.replace('и', '{}{}{}'.format('и', lang, 'и'))
            text6 = text5.replace('И', '{}{}{}'.format('И', lang, 'и'))
            text7 = text6.replace('е', '{}{}{}'.format('е', lang, 'е'))
            text8 = text7.replace('Е', '{}{}{}'.format('Е', lang, 'е'))
            text9 = text8.replace('ё', '{}{}{}'.format('ё', lang, 'ё'))
            text10 = text9.replace('Ё', '{}{}{}'.format('Ё', lang, 'ё'))
            text11 = text10.replace('э', '{}{}{}'.format('э', lang, 'э'))
            text12 = text11.replace('Э', '{}{}{}'.format('Э', lang, 'э'))
            text13 = text12.replace('ы', '{}{}{}'.format('ы', lang, 'ы'))
            text14 = text13.replace('Ы', '{}{}{}'.format('Ы', lang, 'ы'))
            text15 = text14.replace('у', '{}{}{}'.format('у', lang, 'у'))
            text16 = text15.replace('У', '{}{}{}'.format('У', lang, 'а'))
            text17 = text16.replace('ю', '{}{}{}'.format('ю', lang, 'ю'))
            text18 = text17.replace('Ю', '{}{}{}'.format('Ю', lang, 'ю'))
            text19 = text18.replace('я', '{}{}{}'.format('я', lang, 'я'))
            text20 = text19.replace('Я', '{}{}{}'.format('Я', lang, 'я'))
            print(text20)
elif ch == 2:
    for i in range(0, 100):
        i += 1
        text = input('Введите текст:')
        lang = input('Выберите поросячий язык:')
        if lang in w:
            text1 = text.replace('{}{}{}'.format('а', lang, 'а'), 'а')
            text2 = text1.replace('{}{}{}'.format('А', lang, 'а'), 'А')
            text3 = text2.replace('{}{}{}'.format('о', lang, 'о'), 'о')
            text4 = text3.replace('{}{}{}'.format('О', lang, 'о'), 'О')
            text5 = text4.replace('{}{}{}'.format('и', lang, 'и'), 'и')
            text6 = text5.replace('{}{}{}'.format('И', lang, 'и'), 'И')
            text7 = text6.replace('{}{}{}'.format('е', lang, 'е'), 'е')
            text8 = text7.replace('{}{}{}'.format('Е', lang, 'е'), 'Е')
            text9 = text8.replace('{}{}{}'.format('ё', lang, 'ё'), 'ё')
            text10 = text9.replace('{}{}{}'.format('Ё', lang, 'ё'), 'Ё')
            text11 = text10.replace('{}{}{}'.format('э', lang, 'э'), 'э')
            text12 = text11.replace('{}{}{}'.format('Э', lang, 'э'), 'Э')
            text13 = text12.replace('{}{}{}'.format('ы', lang, 'ы'), 'ы')
            text14 = text13.replace('{}{}{}'.format('Ы', lang, 'ы'), 'Ы')
            text15 = text14.replace('{}{}{}'.format('у', lang, 'у'), 'у')
            text16 = text15.replace('{}{}{}'.format('У', lang, 'у'), 'У')
            text17 = text16.replace('{}{}{}'.format('ю', lang, 'ю'), 'ю')
            text18 = text17.replace('{}{}{}'.format('Ю', lang, 'ю'), 'Ю')
            text19 = text18.replace('{}{}{}'.format('я', lang, 'я'), 'я')
            text20 = text19.replace('{}{}{}'.format('Я', lang, 'я'), 'Я')
            print(text20)